name: Unit Tests
description: "Runs SDK's unit tests + linters and optionally gathers coverage."
inputs:
  lint:
    description: "Whether to run linters."
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - uses: ./.github/actions/get-go-version
      id: go-version
    - name: Lint
      if: inputs.lint == 'true'
      shell: bash
      run: make lint

    - name: Test
      shell: bash
      id: test
      run: make test
