version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gosec
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 1000
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
    goimports:
      local-prefixes:
        - gopkg.in/launchdarkly
        - github.com/launchdarkly
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
