name: Common CI
on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version to use for the jobs."
        required: true
        type: string

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: "Unit Tests"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - uses: ./.github/actions/unit-tests
        with:
          lint: "true"
