name: Run Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # v4.2.0
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445
        with:
          target-branch: main
